spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/G118?currentSchema=security
    username: postgres
    password: 12070107Don
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080